# Generated by Django 4.2.3 on 2023-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marvel',
            fields=[
                ('mname', models.CharField(max_length=10)),
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('mlan', models.CharField(max_length=10)),
            ],
        ),
    ]
